name:                coal
version:             0.1.0.0
synopsis:            The Coal programming language and compiler
license:             MIT
license-file:        LICENSE
author:              "Heikki Johannes Hildén"
maintainer:          "hildenjohannes@gmail.com"
copyright:           "2020-present Heikki Johannes Hildén"

homepage:            https://coal-lang.org
bug-reports:         https://codeberg.org/laserpants/coal/issues

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README at <https://codeberg.org/laserpants/coal/src/branch/main/README.md>

dependencies:
- base >= 4.7 && < 5
- data-fix
- text
- text-show
- bytestring
- containers
- mtl
- data-fix
- parser-combinators
- free
- megaparsec
- extra
- recursion-schemes
- uniplate
- deriving-compat
- raw-strings-qq
- process
- prettyprinter
- filepath
- temporary
- directory
- file-embed
- ascii-progress
- data-default
- binary
- cryptonite
- memory
- process-extras
- exceptions >= 0.10.5
- transformers
- pretty-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path 

library:
  source-dirs: src

executables:
  coal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coal
    - optparse-applicative
    - template-haskell
    - aeson
    - aeson-pretty
    - semver

tests:
  coal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coal
    - hspec
