name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"


jobs: 
  build: 
    runs-on: codeberg-small 

    container: 
      image: ghcr.io/laserpants/coal-dev:latest 

    steps: 
      - uses: https://code.forgejo.org/actions/checkout@v6 

      - run: bash coal-install

      - run: stack test --ta '--match Unit --match Kernel'

      - run: coal --version
