name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
jobs:
  build:
    runs-on: codeberg-small

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker run \
            --rm \
            -v "$PWD:/workspace" \
            -w /workspace \
            ghcr.io/laserpants/coal-dev:latest \
            bash scripts/coal-install.sh

      - run: stack test --ta '--match Unit --match Kernel'

      - run: coal --version
