FROM ghcr.io/laserpants/coal-dev

ARG COAL_VERSION

ENV COAL_VERSION=$COAL_VERSION

WORKDIR /src

COPY . .

RUN runtime/scripts/combine.sh && \
    stack install --local-bin-path /usr/local/bin --copy-bins

ENTRYPOINT ["coal"]
